enum ChaosFactor {
  One = 1,
  Two = 2,
  Three = 3,
  Four = 4,
  Five = 5,
  Six = 6,
  Seven = 7,
  Eight = 8,
  Nine = 9,
}

enum Odds {
  Impossible = 0,
  NoWay = 1,
  VeryUnlikely = 2,
  Unlikely = 3,
  FiftyFifty = 4,
  SomewhatLikely = 5,
  Likely = 6,
  VeryLikely = 7,
  NearSureThing = 8,
  ASureThing = 9,
  HasToBe = 10,
}

const oddsMap = {
  [Odds.Impossible]: 'Impossible',
  [Odds.NoWay]: 'No Way',
  [Odds.VeryUnlikely]: 'Very Unlikely',
  [Odds.Unlikely]: 'Unlikely',
  [Odds.FiftyFifty]: '50/50',
  [Odds.SomewhatLikely]: 'Somewhat Likely',
  [Odds.Likely]: 'Likely',
  [Odds.VeryLikely]: 'Very Likely',
  [Odds.NearSureThing]: 'Near Sure Thing',
  [Odds.ASureThing]: 'A Sure Thing',
  [Odds.HasToBe]: 'Has To Be',
}

// nested object representing a fate chart
// outer key is the chaos factor
// inner key are the odds
// value is the chance of a yes
const fateChart: Record<ChaosFactor, Record<Odds, number>> = {
  [ChaosFactor.One]: {
    [Odds.Impossible]: -20,
    [Odds.NoWay]: 0,
    [Odds.VeryUnlikely]: 5,
    [Odds.Unlikely]: 5,
    [Odds.FiftyFifty]: 10,
    [Odds.SomewhatLikely]: 20,
    [Odds.Likely]: 25,
    [Odds.VeryLikely]: 45,
    [Odds.NearSureThing]: 50,
    [Odds.ASureThing]: 55,
    [Odds.HasToBe]: 80,
  },
  [ChaosFactor.Two]: {
    [Odds.Impossible]: 0,
    [Odds.NoWay]: 5,
    [Odds.VeryUnlikely]: 5,
    [Odds.Unlikely]: 10,
    [Odds.FiftyFifty]: 15,
    [Odds.SomewhatLikely]: 25,
    [Odds.Likely]: 35,
    [Odds.VeryLikely]: 50,
    [Odds.NearSureThing]: 55,
    [Odds.ASureThing]: 65,
    [Odds.HasToBe]: 85,
  },
  [ChaosFactor.Three]: {
    [Odds.Impossible]: 0,
    [Odds.NoWay]: 5,
    [Odds.VeryUnlikely]: 10,
    [Odds.Unlikely]: 15,
    [Odds.FiftyFifty]: 25,
    [Odds.SomewhatLikely]: 45,
    [Odds.Likely]: 50,
    [Odds.VeryLikely]: 65,
    [Odds.NearSureThing]: 75,
    [Odds.ASureThing]: 80,
    [Odds.HasToBe]: 90,
  },
  [ChaosFactor.Four]: {
    [Odds.Impossible]: 5,
    [Odds.NoWay]: 10,
    [Odds.VeryUnlikely]: 15,
    [Odds.Unlikely]: 20,
    [Odds.FiftyFifty]: 35,
    [Odds.SomewhatLikely]: 50,
    [Odds.Likely]: 55,
    [Odds.VeryLikely]: 75,
    [Odds.NearSureThing]: 80,
    [Odds.ASureThing]: 85,
    [Odds.HasToBe]: 95,
  },
  [ChaosFactor.Five]: {
    [Odds.Impossible]: 5,
    [Odds.NoWay]: 15,
    [Odds.VeryUnlikely]: 25,
    [Odds.Unlikely]: 35,
    [Odds.FiftyFifty]: 50,
    [Odds.SomewhatLikely]: 65,
    [Odds.Likely]: 75,
    [Odds.VeryLikely]: 85,
    [Odds.NearSureThing]: 90,
    [Odds.ASureThing]: 90,
    [Odds.HasToBe]: 95,
  },
  [ChaosFactor.Six]: {
    [Odds.Impossible]: 10,
    [Odds.NoWay]: 25,
    [Odds.VeryUnlikely]: 45,
    [Odds.Unlikely]: 50,
    [Odds.FiftyFifty]: 65,
    [Odds.SomewhatLikely]: 80,
    [Odds.Likely]: 85,
    [Odds.VeryLikely]: 90,
    [Odds.NearSureThing]: 95,
    [Odds.ASureThing]: 95,
    [Odds.HasToBe]: 100,
  },
  [ChaosFactor.Seven]: {
    [Odds.Impossible]: 15,
    [Odds.NoWay]: 35,
    [Odds.VeryUnlikely]: 50,
    [Odds.Unlikely]: 55,
    [Odds.FiftyFifty]: 75,
    [Odds.SomewhatLikely]: 85,
    [Odds.Likely]: 90,
    [Odds.VeryLikely]: 95,
    [Odds.NearSureThing]: 95,
    [Odds.ASureThing]: 95,
    [Odds.HasToBe]: 100,
  },
  [ChaosFactor.Eight]: {
    [Odds.Impossible]: 25,
    [Odds.NoWay]: 50,
    [Odds.VeryUnlikely]: 65,
    [Odds.Unlikely]: 75,
    [Odds.FiftyFifty]: 85,
    [Odds.SomewhatLikely]: 90,
    [Odds.Likely]: 95,
    [Odds.VeryLikely]: 95,
    [Odds.NearSureThing]: 100,
    [Odds.ASureThing]: 110,
    [Odds.HasToBe]: 130,
  },
  [ChaosFactor.Nine]: {
    [Odds.Impossible]: 50,
    [Odds.NoWay]: 75,
    [Odds.VeryUnlikely]: 85,
    [Odds.Unlikely]: 90,
    [Odds.FiftyFifty]: 95,
    [Odds.SomewhatLikely]: 95,
    [Odds.Likely]: 100,
    [Odds.VeryLikely]: 105,
    [Odds.NearSureThing]: 115,
    [Odds.ASureThing]: 125,
    [Odds.HasToBe]: 145,
  },
}

export { ChaosFactor, fateChart, Odds, oddsMap }
